// 指定使用 proto3 语法

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pkg/api/v1/cse.proto

// 定义包名，这会映射到 Go 语言的包名

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 组件状态枚举
type ComponentState int32

const (
	ComponentState_STATE_UNKNOWN ComponentState = 0
	ComponentState_NOT_LOADED    ComponentState = 1
	ComponentState_LOADED        ComponentState = 2
	ComponentState_INITIALIZED   ComponentState = 3
	ComponentState_RUNNING       ComponentState = 4
	ComponentState_UPDATING      ComponentState = 5
	ComponentState_UNLOADING     ComponentState = 6
	ComponentState_UNLOADED      ComponentState = 7
	ComponentState_ERROR         ComponentState = 8
)

// Enum value maps for ComponentState.
var (
	ComponentState_name = map[int32]string{
		0: "STATE_UNKNOWN",
		1: "NOT_LOADED",
		2: "LOADED",
		3: "INITIALIZED",
		4: "RUNNING",
		5: "UPDATING",
		6: "UNLOADING",
		7: "UNLOADED",
		8: "ERROR",
	}
	ComponentState_value = map[string]int32{
		"STATE_UNKNOWN": 0,
		"NOT_LOADED":    1,
		"LOADED":        2,
		"INITIALIZED":   3,
		"RUNNING":       4,
		"UPDATING":      5,
		"UNLOADING":     6,
		"UNLOADED":      7,
		"ERROR":         8,
	}
)

func (x ComponentState) Enum() *ComponentState {
	p := new(ComponentState)
	*p = x
	return p
}

func (x ComponentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComponentState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_v1_cse_proto_enumTypes[0].Descriptor()
}

func (ComponentState) Type() protoreflect.EnumType {
	return &file_pkg_api_v1_cse_proto_enumTypes[0]
}

func (x ComponentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComponentState.Descriptor instead.
func (ComponentState) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_v1_cse_proto_rawDescGZIP(), []int{0}
}

// [新增] 用于封装命令参数的消息
type CommandParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonPayload   string                 `protobuf:"bytes,1,opt,name=json_payload,json=jsonPayload,proto3" json:"json_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandParams) Reset() {
	*x = CommandParams{}
	mi := &file_pkg_api_v1_cse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandParams) ProtoMessage() {}

func (x *CommandParams) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_cse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandParams.ProtoReflect.Descriptor instead.
func (*CommandParams) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_cse_proto_rawDescGZIP(), []int{0}
}

func (x *CommandParams) GetJsonPayload() string {
	if x != nil {
		return x.JsonPayload
	}
	return ""
}

// [新增] 用于封装命令返回结果的消息
type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonPayload   string                 `protobuf:"bytes,1,opt,name=json_payload,json=jsonPayload,proto3" json:"json_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_pkg_api_v1_cse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_cse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_cse_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResult) GetJsonPayload() string {
	if x != nil {
		return x.JsonPayload
	}
	return ""
}

// [已更新] ExecuteCommand 方法的请求体
type ExecuteCommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 要执行的命令名称
	CommandName string `protobuf:"bytes,1,opt,name=command_name,json=commandName,proto3" json:"command_name,omitempty"`
	// 命令所需的参数
	Params        *CommandParams `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandRequest) Reset() {
	*x = ExecuteCommandRequest{}
	mi := &file_pkg_api_v1_cse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandRequest) ProtoMessage() {}

func (x *ExecuteCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_cse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandRequest.ProtoReflect.Descriptor instead.
func (*ExecuteCommandRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_cse_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteCommandRequest) GetCommandName() string {
	if x != nil {
		return x.CommandName
	}
	return ""
}

func (x *ExecuteCommandRequest) GetParams() *CommandParams {
	if x != nil {
		return x.Params
	}
	return nil
}

// [已更新] ExecuteCommand 方法的响应体
type ExecuteCommandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 命令是否执行成功
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 命令执行返回的结果
	Result *CommandResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	// 如果执行失败，此字段包含错误信息
	ErrorMessage  string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandResponse) Reset() {
	*x = ExecuteCommandResponse{}
	mi := &file_pkg_api_v1_cse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandResponse) ProtoMessage() {}

func (x *ExecuteCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_cse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandResponse.ProtoReflect.Descriptor instead.
func (*ExecuteCommandResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_cse_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteCommandResponse) GetResult() *CommandResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecuteCommandResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// GetMetadata 方法的请求体 (空)
type GetMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	mi := &file_pkg_api_v1_cse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_cse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_cse_proto_rawDescGZIP(), []int{4}
}

// 组件的元数据信息
type ComponentMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version          string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Author           string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	ProvidedCommands []*CommandInfo         `protobuf:"bytes,5,rep,name=provided_commands,json=providedCommands,proto3" json:"provided_commands,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ComponentMetadata) Reset() {
	*x = ComponentMetadata{}
	mi := &file_pkg_api_v1_cse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentMetadata) ProtoMessage() {}

func (x *ComponentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_cse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentMetadata.ProtoReflect.Descriptor instead.
func (*ComponentMetadata) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_cse_proto_rawDescGZIP(), []int{5}
}

func (x *ComponentMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComponentMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ComponentMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ComponentMetadata) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ComponentMetadata) GetProvidedCommands() []*CommandInfo {
	if x != nil {
		return x.ProvidedCommands
	}
	return nil
}

// 单个命令的详细信息
type CommandInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CommandName      string                 `protobuf:"bytes,1,opt,name=command_name,json=commandName,proto3" json:"command_name,omitempty"`
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ParametersSchema string                 `protobuf:"bytes,3,opt,name=parameters_schema,json=parametersSchema,proto3" json:"parameters_schema,omitempty"`
	ResultSchema     string                 `protobuf:"bytes,4,opt,name=result_schema,json=resultSchema,proto3" json:"result_schema,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CommandInfo) Reset() {
	*x = CommandInfo{}
	mi := &file_pkg_api_v1_cse_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandInfo) ProtoMessage() {}

func (x *CommandInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_cse_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandInfo.ProtoReflect.Descriptor instead.
func (*CommandInfo) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_cse_proto_rawDescGZIP(), []int{6}
}

func (x *CommandInfo) GetCommandName() string {
	if x != nil {
		return x.CommandName
	}
	return ""
}

func (x *CommandInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CommandInfo) GetParametersSchema() string {
	if x != nil {
		return x.ParametersSchema
	}
	return ""
}

func (x *CommandInfo) GetResultSchema() string {
	if x != nil {
		return x.ResultSchema
	}
	return ""
}

// GetStatus 方法的请求体 (空)
type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_pkg_api_v1_cse_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_cse_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_cse_proto_rawDescGZIP(), []int{7}
}

// GetStatus 方法的响应体
type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentState  ComponentState         `protobuf:"varint,1,opt,name=current_state,json=currentState,proto3,enum=v1.ComponentState" json:"current_state,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_pkg_api_v1_cse_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_cse_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_cse_proto_rawDescGZIP(), []int{8}
}

func (x *GetStatusResponse) GetCurrentState() ComponentState {
	if x != nil {
		return x.CurrentState
	}
	return ComponentState_STATE_UNKNOWN
}

func (x *GetStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Shutdown 方法的请求体 (空)
type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_pkg_api_v1_cse_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_cse_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_cse_proto_rawDescGZIP(), []int{9}
}

// Shutdown 方法的响应体
type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_pkg_api_v1_cse_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_cse_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_cse_proto_rawDescGZIP(), []int{10}
}

func (x *ShutdownResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *ShutdownResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ComponentName  string                 `protobuf:"bytes,1,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	NewVersionPath string                 `protobuf:"bytes,2,opt,name=new_version_path,json=newVersionPath,proto3" json:"new_version_path,omitempty"`
	Checksum       string                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateNotificationRequest) Reset() {
	*x = UpdateNotificationRequest{}
	mi := &file_pkg_api_v1_cse_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationRequest) ProtoMessage() {}

func (x *UpdateNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_cse_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotificationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_cse_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateNotificationRequest) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *UpdateNotificationRequest) GetNewVersionPath() string {
	if x != nil {
		return x.NewVersionPath
	}
	return ""
}

func (x *UpdateNotificationRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type UpdateNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationResponse) Reset() {
	*x = UpdateNotificationResponse{}
	mi := &file_pkg_api_v1_cse_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationResponse) ProtoMessage() {}

func (x *UpdateNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_cse_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationResponse.ProtoReflect.Descriptor instead.
func (*UpdateNotificationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_cse_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateNotificationResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *UpdateNotificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ComponentVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComponentName string                 `protobuf:"bytes,1,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentVersionRequest) Reset() {
	*x = ComponentVersionRequest{}
	mi := &file_pkg_api_v1_cse_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentVersionRequest) ProtoMessage() {}

func (x *ComponentVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_cse_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentVersionRequest.ProtoReflect.Descriptor instead.
func (*ComponentVersionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_cse_proto_rawDescGZIP(), []int{13}
}

func (x *ComponentVersionRequest) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

type ComponentVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentVersionResponse) Reset() {
	*x = ComponentVersionResponse{}
	mi := &file_pkg_api_v1_cse_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentVersionResponse) ProtoMessage() {}

func (x *ComponentVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_cse_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentVersionResponse.ProtoReflect.Descriptor instead.
func (*ComponentVersionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_cse_proto_rawDescGZIP(), []int{14}
}

func (x *ComponentVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ComponentVersionResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type RegisterComponentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GrpcAddress   string                 `protobuf:"bytes,2,opt,name=grpc_address,json=grpcAddress,proto3" json:"grpc_address,omitempty"`
	Pid           int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterComponentRequest) Reset() {
	*x = RegisterComponentRequest{}
	mi := &file_pkg_api_v1_cse_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterComponentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterComponentRequest) ProtoMessage() {}

func (x *RegisterComponentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_cse_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterComponentRequest.ProtoReflect.Descriptor instead.
func (*RegisterComponentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_cse_proto_rawDescGZIP(), []int{15}
}

func (x *RegisterComponentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterComponentRequest) GetGrpcAddress() string {
	if x != nil {
		return x.GrpcAddress
	}
	return ""
}

func (x *RegisterComponentRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type RegisterComponentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterComponentResponse) Reset() {
	*x = RegisterComponentResponse{}
	mi := &file_pkg_api_v1_cse_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterComponentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterComponentResponse) ProtoMessage() {}

func (x *RegisterComponentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_cse_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterComponentResponse.ProtoReflect.Descriptor instead.
func (*RegisterComponentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_cse_proto_rawDescGZIP(), []int{16}
}

func (x *RegisterComponentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterComponentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_api_v1_cse_proto protoreflect.FileDescriptor

const file_pkg_api_v1_cse_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/api/v1/cse.proto\x12\x02v1\"2\n" +
	"\rCommandParams\x12!\n" +
	"\fjson_payload\x18\x01 \x01(\tR\vjsonPayload\"2\n" +
	"\rCommandResult\x12!\n" +
	"\fjson_payload\x18\x01 \x01(\tR\vjsonPayload\"e\n" +
	"\x15ExecuteCommandRequest\x12!\n" +
	"\fcommand_name\x18\x01 \x01(\tR\vcommandName\x12)\n" +
	"\x06params\x18\x02 \x01(\v2\x11.v1.CommandParamsR\x06params\"\x82\x01\n" +
	"\x16ExecuteCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12)\n" +
	"\x06result\x18\x02 \x01(\v2\x11.v1.CommandResultR\x06result\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x14\n" +
	"\x12GetMetadataRequest\"\xb9\x01\n" +
	"\x11ComponentMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12<\n" +
	"\x11provided_commands\x18\x05 \x03(\v2\x0f.v1.CommandInfoR\x10providedCommands\"\xa4\x01\n" +
	"\vCommandInfo\x12!\n" +
	"\fcommand_name\x18\x01 \x01(\tR\vcommandName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12+\n" +
	"\x11parameters_schema\x18\x03 \x01(\tR\x10parametersSchema\x12#\n" +
	"\rresult_schema\x18\x04 \x01(\tR\fresultSchema\"\x12\n" +
	"\x10GetStatusRequest\"f\n" +
	"\x11GetStatusResponse\x127\n" +
	"\rcurrent_state\x18\x01 \x01(\x0e2\x12.v1.ComponentStateR\fcurrentState\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x11\n" +
	"\x0fShutdownRequest\"P\n" +
	"\x10ShutdownResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x88\x01\n" +
	"\x19UpdateNotificationRequest\x12%\n" +
	"\x0ecomponent_name\x18\x01 \x01(\tR\rcomponentName\x12(\n" +
	"\x10new_version_path\x18\x02 \x01(\tR\x0enewVersionPath\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\tR\bchecksum\"Z\n" +
	"\x1aUpdateNotificationResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"@\n" +
	"\x17ComponentVersionRequest\x12%\n" +
	"\x0ecomponent_name\x18\x01 \x01(\tR\rcomponentName\"J\n" +
	"\x18ComponentVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"c\n" +
	"\x18RegisterComponentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fgrpc_address\x18\x02 \x01(\tR\vgrpcAddress\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\"O\n" +
	"\x19RegisterComponentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x93\x01\n" +
	"\x0eComponentState\x12\x11\n" +
	"\rSTATE_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"NOT_LOADED\x10\x01\x12\n" +
	"\n" +
	"\x06LOADED\x10\x02\x12\x0f\n" +
	"\vINITIALIZED\x10\x03\x12\v\n" +
	"\aRUNNING\x10\x04\x12\f\n" +
	"\bUPDATING\x10\x05\x12\r\n" +
	"\tUNLOADING\x10\x06\x12\f\n" +
	"\bUNLOADED\x10\a\x12\t\n" +
	"\x05ERROR\x10\b2\x92\x02\n" +
	"\x10ComponentService\x12I\n" +
	"\x0eExecuteCommand\x12\x19.v1.ExecuteCommandRequest\x1a\x1a.v1.ExecuteCommandResponse\"\x00\x12>\n" +
	"\vGetMetadata\x12\x16.v1.GetMetadataRequest\x1a\x15.v1.ComponentMetadata\"\x00\x12:\n" +
	"\tGetStatus\x12\x14.v1.GetStatusRequest\x1a\x15.v1.GetStatusResponse\"\x00\x127\n" +
	"\bShutdown\x12\x13.v1.ShutdownRequest\x1a\x14.v1.ShutdownResponse\"\x002\xca\x01\n" +
	"\x1aUpdaterNotificationService\x12X\n" +
	"\x15NotifyUpdateAvailable\x12\x1d.v1.UpdateNotificationRequest\x1a\x1e.v1.UpdateNotificationResponse\"\x00\x12R\n" +
	"\x13GetComponentVersion\x12\x1b.v1.ComponentVersionRequest\x1a\x1c.v1.ComponentVersionResponse\"\x002o\n" +
	"\x19ComponentDiscoveryService\x12R\n" +
	"\x11RegisterComponent\x12\x1c.v1.RegisterComponentRequest\x1a\x1d.v1.RegisterComponentResponse\"\x00B\x13Z\x11cse-go/pkg/api/v1b\x06proto3"

var (
	file_pkg_api_v1_cse_proto_rawDescOnce sync.Once
	file_pkg_api_v1_cse_proto_rawDescData []byte
)

func file_pkg_api_v1_cse_proto_rawDescGZIP() []byte {
	file_pkg_api_v1_cse_proto_rawDescOnce.Do(func() {
		file_pkg_api_v1_cse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_v1_cse_proto_rawDesc), len(file_pkg_api_v1_cse_proto_rawDesc)))
	})
	return file_pkg_api_v1_cse_proto_rawDescData
}

var file_pkg_api_v1_cse_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_api_v1_cse_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_pkg_api_v1_cse_proto_goTypes = []any{
	(ComponentState)(0),                // 0: v1.ComponentState
	(*CommandParams)(nil),              // 1: v1.CommandParams
	(*CommandResult)(nil),              // 2: v1.CommandResult
	(*ExecuteCommandRequest)(nil),      // 3: v1.ExecuteCommandRequest
	(*ExecuteCommandResponse)(nil),     // 4: v1.ExecuteCommandResponse
	(*GetMetadataRequest)(nil),         // 5: v1.GetMetadataRequest
	(*ComponentMetadata)(nil),          // 6: v1.ComponentMetadata
	(*CommandInfo)(nil),                // 7: v1.CommandInfo
	(*GetStatusRequest)(nil),           // 8: v1.GetStatusRequest
	(*GetStatusResponse)(nil),          // 9: v1.GetStatusResponse
	(*ShutdownRequest)(nil),            // 10: v1.ShutdownRequest
	(*ShutdownResponse)(nil),           // 11: v1.ShutdownResponse
	(*UpdateNotificationRequest)(nil),  // 12: v1.UpdateNotificationRequest
	(*UpdateNotificationResponse)(nil), // 13: v1.UpdateNotificationResponse
	(*ComponentVersionRequest)(nil),    // 14: v1.ComponentVersionRequest
	(*ComponentVersionResponse)(nil),   // 15: v1.ComponentVersionResponse
	(*RegisterComponentRequest)(nil),   // 16: v1.RegisterComponentRequest
	(*RegisterComponentResponse)(nil),  // 17: v1.RegisterComponentResponse
}
var file_pkg_api_v1_cse_proto_depIdxs = []int32{
	1,  // 0: v1.ExecuteCommandRequest.params:type_name -> v1.CommandParams
	2,  // 1: v1.ExecuteCommandResponse.result:type_name -> v1.CommandResult
	7,  // 2: v1.ComponentMetadata.provided_commands:type_name -> v1.CommandInfo
	0,  // 3: v1.GetStatusResponse.current_state:type_name -> v1.ComponentState
	3,  // 4: v1.ComponentService.ExecuteCommand:input_type -> v1.ExecuteCommandRequest
	5,  // 5: v1.ComponentService.GetMetadata:input_type -> v1.GetMetadataRequest
	8,  // 6: v1.ComponentService.GetStatus:input_type -> v1.GetStatusRequest
	10, // 7: v1.ComponentService.Shutdown:input_type -> v1.ShutdownRequest
	12, // 8: v1.UpdaterNotificationService.NotifyUpdateAvailable:input_type -> v1.UpdateNotificationRequest
	14, // 9: v1.UpdaterNotificationService.GetComponentVersion:input_type -> v1.ComponentVersionRequest
	16, // 10: v1.ComponentDiscoveryService.RegisterComponent:input_type -> v1.RegisterComponentRequest
	4,  // 11: v1.ComponentService.ExecuteCommand:output_type -> v1.ExecuteCommandResponse
	6,  // 12: v1.ComponentService.GetMetadata:output_type -> v1.ComponentMetadata
	9,  // 13: v1.ComponentService.GetStatus:output_type -> v1.GetStatusResponse
	11, // 14: v1.ComponentService.Shutdown:output_type -> v1.ShutdownResponse
	13, // 15: v1.UpdaterNotificationService.NotifyUpdateAvailable:output_type -> v1.UpdateNotificationResponse
	15, // 16: v1.UpdaterNotificationService.GetComponentVersion:output_type -> v1.ComponentVersionResponse
	17, // 17: v1.ComponentDiscoveryService.RegisterComponent:output_type -> v1.RegisterComponentResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_api_v1_cse_proto_init() }
func file_pkg_api_v1_cse_proto_init() {
	if File_pkg_api_v1_cse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_v1_cse_proto_rawDesc), len(file_pkg_api_v1_cse_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_pkg_api_v1_cse_proto_goTypes,
		DependencyIndexes: file_pkg_api_v1_cse_proto_depIdxs,
		EnumInfos:         file_pkg_api_v1_cse_proto_enumTypes,
		MessageInfos:      file_pkg_api_v1_cse_proto_msgTypes,
	}.Build()
	File_pkg_api_v1_cse_proto = out.File
	file_pkg_api_v1_cse_proto_goTypes = nil
	file_pkg_api_v1_cse_proto_depIdxs = nil
}
